<?php
$data['produtos']=[
    [
        'id'=>'1',
        'empresa'=>'Google',
        'produto'=>'LAMP',
        'disco'=>'',
        'ram'=>'',
        'transferencia'=>'',
        'moeda'=>'',
        'preco'=>'',
        'created_at'=>'',
        'updated_at'=>''
    ],
    [
        'id'=>'2',
        'empresa'=>'Microsoft',
        'produto'=>'LAMP',
        'disco'=>'',
        'ram'=>'',
        'transferencia'=>'',
        'moeda'=>'',
        'preco'=>'',
        'created_at'=>'',
        'updated_at'=>''
    ]
];
view('home',$data);
